Trade Test/Trade Test Web/Controllers/CharacterController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

using Trade_Test.Models;
using Trade_Test.Services.Interfaces;

using X.PagedList;

namespace Trade_Test.Controllers {

    [Authorize(Roles = "Admin")]
    public class CharacterController : Controller {

        private readonly ICharacterService _characterService;

        public CharacterController(
            ICharacterService characterService
            ) {
            _characterService = characterService;
        }

        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page) {

            ViewBag.CurrentSort = sortOrder;
            ViewBag.PageName = "Disney Character List";
            ViewBag.NameSortParam = string.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.CreatedDateSortParam = sortOrder == "CreatedDate" ? "createddate_desc" : "CreatedDate";
            ViewBag.ModifiedDateSortParam = sortOrder == "ModifiedDate" ? "modifieddate_desc" : "ModifiedDate";

            var charactersList = _characterService.GetCharacters();

            if (searchString != null) {
                page = 1;
            }
            else {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            if (!string.IsNullOrEmpty(searchString)) {
                charactersList = charactersList.Where(s => s.Name.Contains(searchString)
                                       || s.Vote.ToString().Contains(searchString)
                                       || s.CreatedDateTime.ToString().Contains(searchString)
                                       || s.ModifiedDateTime.ToString().Contains(searchString)
                                       ).ToList();
            }

            charactersList = sortOrder switch {
                "name_desc" => charactersList.OrderByDescending(s => s.Name).ToList(),
                "CreatedDate" => charactersList.OrderBy(s => s.CreatedDateTime).ToList(),
                "createddate_desc" => charactersList.OrderByDescending(s => s.CreatedDateTime).ToList(),
                "ModifiedDate" => charactersList.OrderBy(s => s.ModifiedDateTime).ToList(),
                "modifieddate_desc" => charactersList.OrderByDescending(s => s.ModifiedDateTime).ToList(),
                _ => charactersList.OrderBy(s => s.Name).ToList(),
            };

            int pageSize = 3;
            int pageNumber = (page ?? 1);

            return View(charactersList.ToPagedList(pageNumber, pageSize));
        }


        public ActionResult CharacterDetail(int id) {

            ViewBag.PageName = "Character Detail";

            var character = _characterService.GetCharacter(id);

            return View(character);
        }

        public ActionResult AddCharacter() {

            ViewBag.PageName = "Add Character";

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddCharacter([Bind("Id,Name,Vote")] Character character) {

            if (ModelState.IsValid) {
                try {
                    _characterService.AddCharacter(character);
                }
                catch (DbUpdateConcurrencyException) {
                    throw;
                }

                return RedirectToAction(nameof(Index));
            }

            return View(character);
        }

        public ActionResult UpdateCharacter(int id) {

            ViewBag.PageName = "Update Character";

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UpdateCharacter(int id, [Bind("Id,Name,Vote")] Character character) {

            if (ModelState.IsValid) {
                try {
                    _characterService.UpdateCharacter(character);
                }
                catch (DbUpdateConcurrencyException) {
                    throw;
                }

                return RedirectToAction(nameof(Index));
            }

            return View(character);
        }
    }
}

Trade Test/Trade Test Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Trade_Test_Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    @* <link rel="stylesheet" href="~/Trade_Test_Web.styles.css" asp-append-version="true" /> *@
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Trade_Test_Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Character" asp-action="Index">Characters List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Index">Users List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Reports" asp-action="Index">Reports</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Trade_Test_Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>